name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup the builder
        run: bash scripts/update-builder.sh

      - name: Build
        run: bash scripts/build.sh --skip-validation --skip-updates
