name: Nexus Mods

on:
  push:
    tags:
    - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Download the release asset
      run: wget "https://github.com/hmlendea/stellaris-ui-name-lists/releases/download/${{inputs.tag}}/ui-name-lists_${GITHUB_REF:11}.zip" -O "release.zip"

    - name: Upload
      uses: Nexus-Mods/upload-action@v1.0.0-beta.3
      with:
        api_key: ${{ secrets.NEXUSMODS_API_KEY }}
        file_group_id: 918667
        filename: release.zip
        display_name: ui-name-lists.zip
        version: ${{inputs.tag}}
        description: "Changelog: https://github.com/hmlendea/stellaris-ui-name-lists/releases/${{inputs.tag}}"
        file_category: main
